SafeCars/Controllers/AdvertisementController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Data.Entity.Validation;
using System.Drawing;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using SafeCars.DataContext;
using SafeCars.Models;

namespace SafeCars.Controllers
{
    public class AdvertisementController : Controller
    {
        private DBDataContext db = new DBDataContext();
        [AllowAnonymous]
        public ActionResult CreateAdvertisement(int idCar) // po testach bez ?
        {
            Session["idCar"] = idCar.ToString();
            return View();
        }

        [HttpPost]
        [AllowAnonymous]
        [ValidateAntiForgeryToken]
        public ActionResult CreateAdvertisement([Bind(Include = "id_advertisement,id_car,id_user,location,title,location_city,outskirts,description,date_of_issue,update_date,number_of_views,private_ad,price,active,time_of_possession")] AdvertisementModels advertisementModels)
        {
            if (ModelState.IsValid)
            {
                string idCar = Session["idCar"].ToString();
                int idCarInt = Int32.Parse(idCar);
                string idUser = "0";
                try
                {
                    idUser = Session["idUser"].ToString();
                }
                catch (Exception e)
                {
                    return RedirectToAction("Index", "Home");
                }

                int idUserInt = Int32.Parse(idUser);

                advertisementModels.id_car = idCarInt;
                advertisementModels.id_user = idUserInt;
                advertisementModels.date_of_issue = DateTime.Now;
                advertisementModels.update_date = DateTime.Now;
                advertisementModels.active = true;
                advertisementModels.number_of_views = 0;
                advertisementModels.number_of_vin = 0;
                db.Advertisment.Add(advertisementModels);
                db.SaveChanges();

                return RedirectToAction("AddImage");
            }
            return View(advertisementModels);
        }
        [AllowAnonymous]
        public ActionResult AddLocation()
        {
            return View();
        }

        [AllowAnonymous]
        public ActionResult AddImage()
        {
            return View();
        }

        [AcceptVerbs(HttpVerbs.Post)]
        [AllowAnonymous]
        [ValidateAntiForgeryToken]
        public ActionResult AddImage(ImagesModels model)
        {
            HttpPostedFileBase file = Request.Files["myfile"];

            if (file != null)
            {

                model.img = new byte[file.ContentLength];
                file.InputStream.Read(model.img, 0, file.ContentLength);
                db.Images.Add(model);
                db.SaveChanges();

                ImagesModels idImg = db.Images.Where(x => x.img == model.img && x.id_image == model.id_image).FirstOrDefault();
                string idCar = Session["idCar"].ToString();
                int idCarInt = Int32.Parse(idCar);
                ListImagesModels newRecord = new ListImagesModels();
                newRecord.id_image = idImg.id_image;
                newRecord.id_car = idCarInt;
                db.ListImages.Add(newRecord);
                db.SaveChanges();

                List<ListImagesModels> listIdFoto = db.ListImages.Where(x => x.id_car == idCarInt).ToList();
                List<ImagesModels> listFoto = new List<ImagesModels>();
                foreach (var item in listIdFoto)
                {
                    listFoto.Add(db.Images.Where(x => x.id_image == item.id_image).FirstOrDefault());

                }
                List<Image> listImage = new List<Image>();
                List<string> listImageString = new List<string>();
                foreach (var item in listFoto)
                {
                    string imageBase64Data = Convert.ToBase64String(item.img);
                    string imageDataURL = string.Format("data:image/png;base64,{0}", imageBase64Data);
                    listImageString.Add(imageDataURL);
                }

                ViewBag.listAllFoto = listImageString;
                return View();
            }
            else
            {
                return View();
            }

        }

        [AllowAnonymous]
        public ActionResult AdAdded()
        {
            return View();
        }

        [AllowAnonymous]
        public ActionResult AdvertisementView(int id) 
        {
             if (Session["idUser"] != null)
            {
                ViewBag.UserIs = Session["idUser"].ToString();
            }
            else
            {
                 ViewBag.UserIs = "-1";
            }
            AdvertisementModels advModel = db.Advertisment.FirstOrDefault(y => y.id_advertisement == id);
            advModel.number_of_views = advModel.number_of_views + 1;
            try
            {
                db.Entry(advModel).State = EntityState.Modified;
                db.SaveChanges();
            }
            catch (DbEntityValidationException dbEx)
            {
                foreach (var validationErrors in dbEx.EntityValidationErrors)
                {
                    foreach (var validationError in validationErrors.ValidationErrors)
                    {
                        System.Console.WriteLine("Property: {0} Error: {1}", validationError.PropertyName, validationError.ErrorMessage);
                    }
                }
            }

            CarModels carModel = db.Car.FirstOrDefault(y => y.id_car == advModel.id_car);
            List<ListImagesModels> listImageId = db.ListImages.Where(y => y.id_car == advModel.id_car).ToList();
            List<ImagesModels> listImage = new List<ImagesModels>();
            foreach (var item in listImageId)
            {
                listImage.Add(db.Images.FirstOrDefault(y => y.id_image == item.id_image));
            }
            List<string> listImageString = new List<string>();
            foreach (var item in listImage)
            {
                string imageBase64Data = Convert.ToBase64String(item.img);
                string imageDataURL = string.Format("data:image/png;base64,{0}", imageBase64Data);
                listImageString.Add(imageDataURL);
            }
            UsersModels user = db.Users.FirstOrDefault(y => y.id_user == advModel.id_user);
            CarsModelsModels carModelName = db.CarsModels.FirstOrDefault(y => y.id_cars_models == carModel.id_cars_models);
            CarMakes carMakes = db.CarsMakes.FirstOrDefault(y => y.id_cars_makes == carModelName.id_cars_makes);
            carModelName.carMakes = carMakes;
            carModel.carModels = carModelName;
            advModel.usersModels = user;
            AdvCarImg model = new AdvCarImg();
            model.advModel = advModel;
            model.carModel = carModel;
            model.imgList = listImageString;
            ViewBag.count = 0;

            return View(model);
        }

        [AllowAnonymous]
        [HttpPost]
        public string likeButton(String adv) 
        {
            int pom;
            WatchListModels watchListModels = new WatchListModels();
            Int32.TryParse(adv, out pom);
            watchListModels.id_advertisement = pom;
            string idUser = "-1";


            if (Session["idUser"] != null)
            {
                idUser = Session["idUser"].ToString();
            }
            if (idUser == "-1")
            {
                return "{\"msg\":\"notIdUser\"}";
            }
            int idUserInt;
            Int32.TryParse(idUser, out idUserInt);
            watchListModels.id_user = idUserInt;

            WatchListModels check = db.WatchList.FirstOrDefault(y => y.id_advertisement == watchListModels.id_advertisement && watchListModels.id_user == y.id_user);
            if (check == null)
            {
                db.WatchList.Add(watchListModels);
                db.SaveChanges();
                return "{\"msg\":\"add\"}";
            }
            else
            {
                ViewBag.messlikebutton = "Usunięto";
                db.WatchList.Remove(check);
                db.SaveChanges();
                return "{\"msg\":\"delete\"}";
            }
        }
        public ActionResult ActivateAdv(int id) 
        {
            string idUser = "-1";
            if (Session["idUser"] != null)
            {
                idUser = Session["idUser"].ToString();
            }
            if (idUser == "-1")
            {
                return RedirectToAction("Login", "UsersModels");
            }
            int idUserInt;
            Int32.TryParse(idUser, out idUserInt);
            int count = db.Advertisment.Where(y => y.id_user == idUserInt && y.active == true).Count();
            if (count >= 3)
            {
                return RedirectToAction("UserPage", "UsersModels", new { err = 3 });
            }
            AdvertisementModels adv = db.Advertisment.FirstOrDefault(y => y.id_advertisement == id);

            adv.active = true;
            try
            {
                db.Entry(adv).State = EntityState.Modified;
                db.SaveChanges();
            }
            catch (DbEntityValidationException dbEx)
            {
                foreach (var validationErrors in dbEx.EntityValidationErrors)
                {
                    foreach (var validationError in validationErrors.ValidationErrors)
                    {
                        System.Console.WriteLine("Property: {0} Error: {1}", validationError.PropertyName, validationError.ErrorMessage);
                    }
                }
            }
            return View();
        }
        public ActionResult NotActivateAdv(int id) //zmiien to
        {
            AdvertisementModels adv = db.Advertisment.FirstOrDefault(y => y.id_advertisement == id);
            adv.active = false;
            try
            {

SafeCars/Views/Admin/AddNewCar.cshtml
@model SafeCars.Models.MakeandModel
@{
    ViewBag.Title = "AddNewCar";
    Layout = "~/Views/Shared/_Layout3Admin.cshtml";
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Podaj parametry nowego modelu</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            Podaj markę pojazdu
            <div class="col-md-10">
                @Html.EditorFor(model => model.carMake.name_make, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.carMake.name_make, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            Podaj model pojazdu
            <div class="col-md-10">
                @Html.EditorFor(model => model.carModel.model, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.carModel.model, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            Podaj wersję (jeśli pojazd nie ma określonej wersji pozostaw puste pole)
            <div class="col-md-10">
                @Html.EditorFor(model => model.carModel.version, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.carModel.version, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Dalej" class="btn btn-default" />
            </div>
        </div>
    </div>
}

SafeCars/Views/Admin/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout3Admin.cshtml";
}
<h2>Witaj Administratorze! </h2>

@if (ViewBag.mess != null)
{
    <div class="row justify-content-md-center">
        <div class="col-sm-12 col-md-5">
            <div class="card mt-3">
                <div class="card-header ">
                    Komunikat
                </div>
                <div class="card-body m-2">
                    @ViewBag.mess
                    <img src="~/checksuccess.png" alt="checksuccess" width="60" height="60" />
                </div>
               
            </div>
        </div>
    </div>
}

SafeCars/Views/Admin/ListComplaints.cshtml
@model IEnumerable<SafeCars.Models.ComplaintsModels>
@{
   
    Layout = "~/Views/Shared/_Layout3Admin.cshtml";
}
<table class="table">
    <tr>
        <th style="min-width:700px">
            Opis skargi
        </th>
        <th>
            Ogłoszenie
        </th>
        <th>
            Opcje
        </th>

    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td style="min-width:700px">
                @Html.DisplayFor(modelItem => item.description)
            </td>
            <td>
                <button onclick="location.href='@Url.Action("AdvertisementView", "Advertisement", new {id=item.id_advertisement })'" ; class="btn btn-outline-primary m-3 ">ID=@item.id_advertisement</button>
            </td>
            <td>
                <button onclick="location.href='@Url.Action("BanUser", "Admin", new {id=item.id_advertisement })'" ; class="btn btn-outline-danger m-3 mt-3 mb-1">Zablokuj użytkownika</button>
                <button onclick="location.href='@Url.Action("DeleteComp", "Admin", new {id=item.id_advertisement })'" ; class="btn btn-outline-success m-3 my-1">Anuluj zgłszenia</button>
                <button onclick="location.href='@Url.Action("SendBanMessage", "Admin", new {id=item.id_advertisement })'" ; class="btn btn btn-outline-secondary m-3 my-1">Wyśli upomnienie</button>
            </td>
        </tr>
    }
</table>

SafeCars/Views/Admin/SendBanMessage.cshtml
@model SafeCars.Models.ComplaintsModels
@{
    
    Layout = "~/Views/Shared/_Layout3Admin.cshtml";
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    @Html.Hidden("id_advertisement")
    <div class="form-horizontal">
        <h4>Podaj wiadomość</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            Treść
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.description, 5, 100, htmlAttributes: new { style = "width: 100%; max-width: 100%;" })
                @Html.ValidationMessageFor(model => model.description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Wyśli" class="btn btn-outline-danger" />
            </div>
        </div>
    </div>
}